spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pandora?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Reenukoju7$

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 3038